export const mensas = [
  {
    id: 'imbirch-bircholino',
    name: 'Mensa Bircholino',
    school: 'Schule Im Birch',
    type: 'Städtische Schule',
    district: 'Zürich Nord',
    address: 'Margrit-Rainer-Strasse 5, 8050 Zürich',
    lat: 47.4124,
    lng: 8.5403,
    openingHours: 'Mo–Fr, Mittag offen; Pausenkiosk am Vormittag',
    provider: 'Schule Im Birch / Menu and More im Sek-Treff',
    priceHint: 'Spontane Sek-Anmeldungen werden monatlich abgerechnet.',
    currentMenuLabel: 'Offizieller Wochenmenü-PDF der Schule',
    menuUrl: 'https://www.stadt-zuerich.ch/schulen/de/imbirch/ueberuns/mensa.html',
    sourceUrl: 'https://www.stadt-zuerich.ch/schulen/de/imbirch/ueberuns/mensa.html',
    features: ['Pausenkiosk', 'Sek-Treff', 'TWINT', 'Mensa-Karte'],
    today: [
      { line: 'Wochenmenü', dish: 'Aktueller PDF-Link auf der Schulwebseite', tags: ['offiziell', 'wöchentlich'] },
      { line: 'Sek-Treff', dish: 'Menu-and-More-Wochenplan via Schulwebseite', tags: ['sek', 'extern'] },
    ],
  },
  {
    id: 'neubuehl-verpflegung',
    name: 'Verpflegung Schule Neubühl',
    school: 'Schule Neubühl',
    type: 'Städtische Schule',
    district: 'Wollishofen',
    address: 'Neubühlstrasse 32, 8038 Zürich',
    lat: 47.3389,
    lng: 8.5302,
    openingHours: 'Schulbetreuung, Mittagessen gemäss Betreuung',
    provider: 'Schulküche / Stadt Zürich Richtlinien',
    priceHint: 'Betreuungsangebot der Stadt Zürich.',
    currentMenuLabel: 'Offizielle Menüplan-PDFs der Schule',
    menuUrl: 'https://www.stadt-zuerich.ch/schulen/de/neubuehl/betreuung/verpflegung.html',
    sourceUrl: 'https://www.stadt-zuerich.ch/schulen/de/neubuehl/betreuung/verpflegung.html',
    features: ['Vegetarische Alternative', 'Allergie-Anpassung', 'Frische Salate', 'Hahnenwasser'],
    today: [
      { line: 'Tagesmenü', dish: 'Aktueller Wochenplan als PDF auf der Schulwebseite', tags: ['offiziell'] },
      { line: 'Alternative', dish: 'Vegetarische Alternative gemäss Schulangaben', tags: ['vegetarisch'] },
    ],
  },
  {
    id: 'ks-wiedikon',
    name: 'Mensa Kantonsschule Wiedikon',
    school: 'Kantonsschule Wiedikon',
    type: 'Kantonsschule',
    district: 'Wiedikon',
    address: 'Schrennengasse 7, 8003 Zürich',
    lat: 47.3717,
    lng: 8.5205,
    openingHours: 'Mo–Fr 08:00–15:30, Mi bis 14:00; Mittagsservice 11:30–13:30',
    provider: 'ZFV',
    priceHint: 'Preiswerte Speisen für Schulangehörige und Gäste.',
    currentMenuLabel: 'Wöchentlicher Menüplan der Mensa',
    menuUrl: 'https://www.kwi.ch/dienstleistungen/mensa',
    sourceUrl: 'https://www.kwi.ch/dienstleistungen/mensa',
    features: ['Terrasse', 'öffentlich', 'Snacks', 'Mikrowellen'],
    today: [
      { line: 'Lunch', dish: 'Wöchentlich publizierter Menüplan', tags: ['zfv'] },
      { line: 'Snacks', dish: 'Znüni, Zvieri, Getränke und Kaffee', tags: ['snack'] },
    ],
  },
  {
    id: 'ks-enge-freudenberg',
    name: 'Mensa KS Enge / Freudenberg',
    school: 'Kantonsschulen Enge, Freudenberg und Liceo',
    type: 'Kantonsschule',
    district: 'Enge',
    address: 'Brandschenkestrasse 125, 8002 Zürich',
    lat: 47.3621,
    lng: 8.5259,
    openingHours: 'Mo–Fr 08:00–14:15',
    provider: 'ZFV',
    priceHint: 'Preiswerte Menüs und Znünis.',
    currentMenuLabel: 'Menuplan der gemeinsamen Mensa',
    menuUrl: 'https://www.ken.ch/service/mensa',
    sourceUrl: 'https://www.ken.ch/service/mensa',
    features: ['gemeinsame Mensa', 'Znüni', 'preiswerte Menüs'],
    today: [
      { line: 'Menuplan', dish: 'Offizieller Link auf der KS-Enge-Seite', tags: ['zfv'] },
      { line: 'Cafeteria', dish: 'Znünis und warme Mittagsverpflegung', tags: ['snack'] },
    ],
  },
  {
    id: 'ks-raemibuehl',
    name: 'Mensa Kantonsschule Rämibühl',
    school: 'MNG, LG und RG Rämibühl',
    type: 'Kantonsschule',
    district: 'Hochschulen',
    address: 'Freiestrasse 36, 8032 Zürich',
    lat: 47.3743,
    lng: 8.5522,
    openingHours: 'Schultage, Details beim Betreiber',
    provider: 'ZFV',
    priceHint: 'Mensa-Angebot der ZFV-Unternehmungen.',
    currentMenuLabel: 'ZFV-Menuplan / Newsletter',
    menuUrl: 'https://www.mng.ch/service/mensa/',
    sourceUrl: 'https://www.mng.ch/service/mensa/',
    features: ['Newsletter', 'ZFV', 'Campus Rämibühl'],
    today: [
      { line: 'Tagesmenü', dish: 'Aktueller Menuplan über ZFV-Link der Schule', tags: ['zfv'] },
      { line: 'Newsletter', dish: 'Menuplan kann abonniert werden', tags: ['abo'] },
    ],
  },
  {
    id: 'ks-zuerich-nord',
    name: 'The YARD',
    school: 'Kantonsschule Zürich Nord / Campus Irchel',
    type: 'Kantonsschule',
    district: 'Oerlikon / Irchel',
    address: 'Winterthurerstrasse 190, 8057 Zürich',
    lat: 47.3977,
    lng: 8.5472,
    openingHours: 'Während Schulzeiten Mo–Fr 09:00–14:00',
    provider: 'ZFV',
    priceHint: 'Campus-Verpflegung für Schul- und Universitätsangehörige.',
    currentMenuLabel: 'The-YARD-Menüplan',
    menuUrl: 'https://www.kzn.ch/angebot/dienste/mensa',
    sourceUrl: 'https://www.kzn.ch/angebot/dienste/mensa',
    features: ['Soul Food', 'Rund um den Globus', 'Pausenverpflegung', 'Campus Irchel'],
    today: [
      { line: 'Soul Food', dish: 'Aktuelle Menüs über The-YARD-Link', tags: ['zfv'] },
      { line: 'Globus', dish: 'Internationales Tagesangebot', tags: ['international'] },
    ],
  },
  {
    id: 'freie-schule-waldmannstrasse',
    name: 'Mensa Waldmannstrasse',
    school: 'Freie Schule Zürich',
    type: 'Private Schule',
    district: 'Seefeld',
    address: 'Waldmannstrasse 9, 8001 Zürich',
    lat: 47.3675,
    lng: 8.5484,
    openingHours: 'Schultage, Mittagessen nach Schulbetrieb',
    provider: 'Freie Schule Zürich',
    priceHint: 'Schulinternes Mensa-Angebot.',
    currentMenuLabel: 'Menuplan der Freien Schule Zürich',
    menuUrl: 'https://fsz.ch/mensa-waldmannstrasse/',
    sourceUrl: 'https://fsz.ch/mensa-waldmannstrasse/',
    features: ['frisch gekocht', 'Schulhaus Waldmannstrasse', 'Menuplan online'],
    today: [
      { line: 'Mittag', dish: 'Aktueller Menuplan auf der Schulwebseite', tags: ['offiziell'] },
      { line: 'Küche', dish: 'Täglich frisch gekocht laut Schule', tags: ['frisch'] },
    ],
  },
  {
    id: 'phzh-mensa',
    name: 'Mensa PHZH',
    school: 'Pädagogische Hochschule Zürich',
    type: 'Hochschule',
    district: 'Lagerstrasse',
    address: 'Lagerstrasse 2, 8090 Zürich',
    lat: 47.3774,
    lng: 8.5335,
    openingHours: 'Werktags, gemäss Food2050/ZFV-Plan',
    provider: 'ZFV / Food2050',
    priceHint: 'Hochschulmensa mit wöchentlichem PDF-Menüplan.',
    currentMenuLabel: 'Weekly PDF via Food2050',
    menuUrl: 'https://app.food2050.ch/de/v2/zfv/padagogische-hochschule-zurich/mensa-phzh/mittagsverpflegung/menu/weekly.pdf',
    sourceUrl: 'https://app.food2050.ch/de/v2/zfv/padagogische-hochschule-zurich/mensa-phzh/mittagsverpflegung/menu/weekly.pdf',
    features: ['PDF-Menüplan', 'Hochschule', 'ZFV'],
    today: [
      { line: 'Mittagsmenü', dish: 'Aktueller Wochen-PDF direkt öffnen', tags: ['zfv'] },
      { line: 'Info', dish: 'Allergen- und Detailinfos an der Ausgabe', tags: ['allergene'] },
    ],
  },
]
